# Generated by Django 5.2.12 on 2026-04-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jaibabu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
